name: update

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  buildAndUpdateDist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: install dependencies
        run: npm install
      - name: build dist folder
        run: npm run build
      - name: Commit dist files
        run: |
          git config --local user.name  ${{ github.event.pusher.name }}
          git config --local user.email  ${{ github.event.pusher.email }}
          git add ./dist -f
          git commit -m "[CI] Updating dist files"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
  buildAndUpdatePages:
    if: ${{ always() }}
    needs: [buildAndUpdateDist]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: npm install

      - uses: actions/checkout@v6
        with:
          ref: gh-pages
          path: gh-pages

      - name: Clear subfolder
        run: rm -rf gh-pages/*

      - uses: H0rn0chse/gh-pages-copy-action@main
        with:
          root: ${{ github.workspace }}

      - name: Commit gh-pages files
        continue-on-error: true
        working-directory: ./gh-pages
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit --amend -m "Build gh-pages" --author="github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

      - name: Push changes
        continue-on-error: true
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: ./gh-pages
          force: true
