name: update-dist

on:
  push:
    branches: [main]

jobs:
  buildAndUpdateDist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: install dependencies
        run: npm install
      - name: build dist folder
        run: npm run build
      - name: Commit dist files
        run: |
          git config --local user.name  ${{ github.event.pusher.name }}
          git config --local user.email  ${{ github.event.pusher.email }}
          git add ./dist -f
          git commit -m "[CI] Updating dist files"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
